swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger WyTho
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /commands:
    get:
      operationId: "resources.commands.get_all"
      tags:
        - "command"
      summary: "Object data supported by the server"
      description: "Read the list of objects"
      responses:
        200:
          description: "Successfully read the list of objects"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "number"
                name:
                  type: "string"
                address:
                  type: "string"
                consumption_type_id:
                  type: "number"